name: 🏷️ Auto Tag Release

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    name: Create Git Tag from Pubspec
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: 📖 Extract Version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | cut -d '+' -f 1)
          echo "App version is $VERSION"
          echo "VERSION=v$VERSION" >> $GITHUB_OUTPUT

      - name: 🏷️ Create or Force-Update Tag
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git tag -f ${{ steps.get_version.outputs.VERSION }}
          git push origin refs/tags/${{ steps.get_version.outputs.VERSION }} --force